<a href="https://colab.research.google.com/github/shaambuildon/MACHINE-LEARNING-TECHNIQUES/blob/main/task_5_MLT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_wine # Import load_wine

# Load the wine dataset from scikit-learn
wine = load_wine()
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.Series(wine.target, name='target')

#split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
#standardize the features using only the training data

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
#create a PCA object with the desired number of components
pca = PCA(n_components=2)
#fit the PCA on the scaled training data and transform both training and testing data
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)
#create a Random Forest classifier and fit it on the training data
clf = RandomForestClassifier(random_state=0)
clf.fit(X_train_pca, y_train)
#make predictions on the testing data
y_pred = clf.predict(X_test_pca)
#print the confusion matrix
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))
conf_m= confusion_matrix(y_test, y_pred)
print(conf_m)

Accuracy : 0.9722222222222222
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
